apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
 name: che-tls
 namespace: che
spec:
 secretName: che-tls
 issuerRef:
   name: che-certificate-issuer
   kind: ClusterIssuer
 dnsNames:
   - '*.eclipse8.yaksha.online'
 acme:
   config:
     - dns01:
         provider: route53
       domains:
         - '*.eclipse8.yaksha.online'
